package model;

// Generated 29/11/2018 20:14:38 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "CURSO")
public class Curso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codcurso;
	private String nome;
	private long valor;
	private String url;

	public Curso() {
	}

	public Curso(long codcurso, String nome, long valor, String url) {
		this.codcurso = codcurso;
		this.nome = nome;
		this.valor = valor;
		this.url = url;
	}

	@Id
	@Column(name = "CODCURSO", unique = true, nullable = false, precision = 22, scale = 0)
	public long getCodcurso() {
		return this.codcurso;
	}

	public void setCodcurso(long codcurso) {
		this.codcurso = codcurso;
	}

	@Column(name = "NOME", nullable = false, length = 80)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "VALOR", nullable = false, precision = 22, scale = 0)
	public long getValor() {
		return this.valor;
	}

	public void setValor(long valor) {
		this.valor = valor;
	}

	@Column(name = "URL", nullable = false, length = 80)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	@Override
	public String toString() {
		return "Curso [codcurso="+codcurso+" nome="+nome+" valor="+valor+" url="+url+"]";
	}

}
